# Generated by Django 4.2.3 on 2023-11-01 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingerModel',
            fields=[
                ('singer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('singer_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SongModel',
            fields=[
                ('song_id', models.IntegerField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(default='', max_length=255)),
                ('media_type', models.IntegerField(null=True)),
                ('duration', models.IntegerField(default=0)),
                ('file_path', models.CharField(max_length=255, null=True)),
                ('file_md5', models.CharField(max_length=255, null=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('updated_time', models.TimeField(auto_now=True)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.singermodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('tag_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(default='', max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='SongTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.songmodel')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tagmodel')),
            ],
        ),
    ]
