# Generated by Django 4.2.3 on 2023-12-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usermodel_super_user_alter_singermodel_singer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singermodel',
            name='singer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
