# Generated by Django 4.2.3 on 2023-12-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_songmodel_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songmodel',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='songmodel',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
