# Generated by Django 4.2.3 on 2023-12-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_songmodel_created_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songmodel',
            name='singer',
        ),
        migrations.AddField(
            model_name='songmodel',
            name='singers',
            field=models.ManyToManyField(to='app.singermodel'),
        ),
        migrations.AlterField(
            model_name='songmodel',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
