# Generated by Django 4.2.3 on 2023-12-14 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_songmodel_singer_songmodel_singers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singermodel',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singermodel',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
