# Generated by Django 4.2.3 on 2025-09-21 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='歌手名')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnmatchedMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='音乐文件完整路径', max_length=1024)),
                ('file_name', models.CharField(help_text='音乐文件名', max_length=255)),
                ('elem1', models.CharField(blank=True, help_text='文件名切割后的第一个元素', max_length=255, null=True)),
                ('elem2', models.CharField(blank=True, help_text='文件名切割后的第二个元素', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录时间')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='歌曲名')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='封面图')),
                ('duration', models.IntegerField(default=0)),
                ('play_count', models.PositiveIntegerField(default=0, verbose_name='播放次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('artists', models.ManyToManyField(related_name='songs', to='app.artist', verbose_name='歌手')),
                ('tags', models.ManyToManyField(blank=True, related_name='songs', to='app.tag', verbose_name='标签')),
            ],
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=50)),
                ('file', models.CharField(max_length=255, unique=True)),
                ('size', models.BigIntegerField(default=0)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.song')),
            ],
        ),
        migrations.AddConstraint(
            model_name='audiofile',
            constraint=models.UniqueConstraint(fields=('song', 'file'), name='unique_song_file'),
        ),
    ]
