# Generated by Django 4.2.3 on 2025-02-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_devicemodel_devicesongsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='device_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
